// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs /home/huahua/Desktop/myWorkStation/gobacnet/model/struct_c.go

package gobacnet

type Who struct {
	Device uint32
	Mac    [6]uint8
}
type Wl_array struct {
	Size     int32
	Capacity int32
	Array    *Who
}
